import type { Metadata } from "next";
import JsonLd from "@/components/JsonLd";
import MarketPageClient, { type MarketCopy } from "@/features/markets/MarketPageClient";
import "@/features/markets/markets.css";
import { SITE_URL } from "@/config/seo";

export const metadata: Metadata = {
  title: "شركة برمجة للسوق السعودي | مواقع وأنظمة ومنصات",
  description: "DOMINASE تطور مواقع، أنظمة مخصصة، منصات تعليمية ومواقع وأنظمة عيادات للشركات والمشاريع التي تستهدف السوق السعودي، بعربية واضحة وتجربة موبايل وSEO.",
  alternates: { canonical: "/markets/saudi-arabia" },
  openGraph: { title: "DOMINASE — Software & Digital Products for Saudi Arabia", description: "Web development, custom systems, education platforms and clinic digital products for projects serving Saudi Arabia.", url: `${SITE_URL}/markets/saudi-arabia`, type: "website" },
};

const copy: MarketCopy = {
  ar:{eyebrow:"DOMINASE / السعودية",title:"منتجات رقمية للسوق السعودي: أوضح للعميل، وأسهل للفريق أن يديرها.",lead:"نخدم مشاريع تستهدف السعودية بمواقع ومنصات وأنظمة تركّز على تجربة الهاتف، والعربية الطبيعية، والسرعة، ومسار واضح من الاهتمام إلى الطلب أو الحجز.",intro:"السوق السعودي سريع رقمياً، وتوقعات المستخدم مرتفعة بسبب اعتياده على تطبيقات وخدمات متقنة. هذا لا يعني أن كل مشروع يحتاج عشرات المزايا؛ بل يعني أن الأساسيات يجب أن تكون قوية: رسالة واضحة، وتجربة هاتف مريحة، وثقة، وإجراء مباشر، وأداء لا يبطئ القرار.",needsTitle:"المسارات التي نبنيها للمشاريع التي تستهدف السعودية",needs:[{title:"مواقع الشركات والمنتجات",body:"حضور عربي وإنجليزي منظم، وصفحات خدمات واضحة، وأساس تقني للبحث، ومسارات إجراء تناسب الحملات.",href:"/services/web-development"},{title:"الأنظمة المخصصة",body:"لوحات إدارة وسير عمل يساعدان الفريق على التعامل مع النمو من دون تضاعف العمل اليدوي.",href:"/services/custom-systems"},{title:"المنصات التعليمية",body:"بيع وإدارة المحتوى والطلاب والاختبارات من منتج يحمل هوية الأكاديمية أو المدرب.",href:"/services/education-platforms"},{title:"العيادات والمراكز",body:"من صفحة الخدمة والإعلان إلى حجز واضح، ومصدر طلب محفوظ، ومتابعة أكثر ترتيباً.",href:"/services/clinic-websites"}],approachTitle:"ما الذي نهتم به للسوق السعودي؟",approach:["لغة عربية بيضاء ومهنية لا تبدو مترجمة أو رسمية أكثر من اللازم.","تجربة تبدأ من الهاتف لأن التصفح والحملات والقرار تبدأ منه غالباً.","صفحات خدمات مرتبطة بنية بحث واضحة بدلاً من صفحة رئيسية تحاول قول كل شيء.","إجراء مختلف حسب الخدمة والحملة عندما يختلف قرار المستخدم.","نظام قابل للتوسع مع نمو العملاء أو المدربين أو الفروع أو الموظفين."],seoTitle:"الظهور في البحث داخل السعودية يحتاج محتوى يخدم النية، لا صفحات متشابهة يتغيّر فيها اسم المدينة.",seoBody:"نستخدم صفحات خدمات ذات قيمة، ومحتوى يشرح المشاكل بعمق، وروابط داخلية، وأعمالاً تثبت القدرة. وإذا احتاج المشروع استهداف مدن أو قطاعات مختلفة، نبني صفحات ذات غرض ومحتوى حقيقي بدلاً من صفحات مكررة لمحركات البحث.",finalTitle:"هل يستهدف مشروعك السوق السعودي؟",finalBody:"احكِ لنا عن الجمهور والخدمة وما الذي تريد من العميل أن يفعله بعد الدخول. من هناك نحدد هل الحل موقع أو منصة أو نظاماً أو رحلة تجمع بينها.",finalCta:"ابدأ مشروعك"},
  en:{eyebrow:"DOMINASE / Saudi Arabia",title:"Digital products for Saudi Arabia: clearer for customers and easier for teams to operate.",lead:"We support projects serving Saudi Arabia with websites, platforms, and systems focused on mobile UX, natural Arabic, performance, and a clear path from interest to request or booking.",intro:"Saudi users are accustomed to strong digital services, which raises expectations around speed, mobile experience, clarity, and confirmation. That does not mean every project needs dozens of features; it means the fundamentals need to be excellent.",needsTitle:"What we build for projects serving Saudi Arabia",needs:[{title:"Company and product websites",body:"Structured Arabic and English presence, service pages, SEO, and campaign-aware CTAs.",href:"/services/web-development"},{title:"Custom systems",body:"Admin tools and workflows that help operations scale without multiplying manual work.",href:"/services/custom-systems"},{title:"Education platforms",body:"Branded learning products for selling and managing content, students, and assessments.",href:"/services/education-platforms"},{title:"Clinics and medical centers",body:"From campaign and service page to booking, stored lead context, and clearer follow-up.",href:"/services/clinic-websites"}],approachTitle:"What matters for the Saudi market",approach:["Professional natural Arabic rather than literal translation.","Mobile-first journeys for browsing and campaign traffic.","Service pages matched to search intent.","Different CTAs where user decisions genuinely differ.","Architecture that can grow with customers, instructors, branches, or staff."],seoTitle:"Saudi SEO needs useful topical authority, not duplicate city pages with swapped keywords.",seoBody:"We use valuable service pages, deep explanatory content, internal links, and relevant work proof. Geographic or industry pages are created when they have a real user purpose rather than as doorway pages.",finalTitle:"Serving customers in Saudi Arabia?",finalBody:"Tell us the audience, service, and the action you need customers to take. We can then determine whether the right product is a website, platform, system, or a connected journey.",finalCta:"Start a project"}
};

export default function Page(){return <><JsonLd data={{"@context":"https://schema.org","@type":"WebPage",name:"Software and digital products for Saudi Arabia — DOMINASE",url:`${SITE_URL}/markets/saudi-arabia`,about:{"@id":`${SITE_URL}/#organization`}}}/><MarketPageClient copy={copy}/></>}
