import type { CaseStudy } from "@/features/case-studies/contracts";

export const caseStudies: Record<string, CaseStudy> = {
  "manal-alhihi": {
    slug: "manal-alhihi",
    visualTheme: "training-platform",
    cover: "/assest/resize/manal-alhihi3.png",
    seo: {
      title: "Manal Alhihi Training Platform Case Study | منصة منال الحيحي",
      description: "A bilingual case study about transforming scattered courses, files, and manual follow-up into an organized training platform.",
    },
    content: {
      en: {
        eyebrow: "Training platform case study",
        title: "Manal Alhihi: From scattered courses to an organized training platform",
        positioning: "Turning a training experience built around distributed links, files, and manual follow-up into one clear digital platform for students, courses, attendance, and content.",
        before: {
          title: "Training was spread across too many places.",
          intro: "The learning experience depended on disconnected tools and repeated manual coordination.",
          points: ["Scattered files", "Separate links", "Google Drive", "Manual follow-up", "Unclear attendance", "Message-dependent students", "Administrative burden"],
        },
        transformation: {
          title: "The scattered pieces became one system.",
          body: "Files, links, student records, and attendance signals were reorganized around a central training platform.",
        },
        after: {
          title: "One structured place for learning and administration.",
          intro: "The platform gives students a clearer path and gives administration a calmer operating view.",
          points: ["Student accounts", "Organized courses", "Attendance tracking", "Course trailers", "Ordered content", "Clearer administration"],
        },
        storyboard: {
          title: "A learning journey with visible structure.",
          intro: "The interface carries the same organization from the platform entrance into course discovery and content detail.",
          screenshots: [
            { src: "/assest/resize/manal-alhihi3.png", alt: "Manal Alhihi training platform landing interface", caption: "Platform entrance" },
            { src: "/assest/resize/manal-alhihi1.png", alt: "Organized course content in the Manal Alhihi platform", caption: "Course structure" },
            { src: "/assest/resize/manal-alhihi.png", alt: "Manal Alhihi platform interface overview", caption: "Student experience" },
          ],
        },
        featuresTitle: "Six modules, one training flow.",
        featuresIntro: "Each module solves a specific operational need while remaining connected to the complete learning journey.",
        features: [
          { title: "Student Accounts", description: "A clear personal entry point for every learner." },
          { title: "Course Management", description: "Courses gathered and managed in an ordered structure." },
          { title: "Attendance Tracking", description: "Attendance status visible without manual guesswork." },
          { title: "Course Trailers", description: "A focused preview before students enter a course." },
          { title: "Content Ordering", description: "Learning material presented in a deliberate sequence." },
          { title: "Admin Clarity", description: "A calmer view of students, courses, and follow-up." },
        ],
        result: "The result was not simply a better-looking interface, but a training experience that is clearer to use, manage, and follow.",
        cta: "Start a focused digital product",
        backHome: "Back to portfolio",
        chapters: ["Introduction", "Before", "Transformation", "After", "Storyboard", "System", "Result"],
      },
      ar: {
        eyebrow: "دراسة حالة لمنصة تدريب",
        title: "المدربة منال الحيحي: من دورات مبعثرة إلى منصة تدريب منظمة",
        positioning: "تحويل تجربة التدريب من روابط وملفات موزعة ومتابعة يدوية إلى منصة رقمية تجمع الطلاب، الدورات، الحضور، والمحتوى في مكان واحد واضح.",
        before: {
          title: "كانت تجربة التدريب موزعة بين أماكن كثيرة.",
          intro: "اعتمد مسار التعلم على أدوات منفصلة وتنسيق يدوي متكرر.",
          points: ["ملفات مبعثرة", "روابط متفرقة", "Google Drive", "متابعة يدوية", "حضور غير واضح", "اعتماد الطلاب على الرسائل", "عبء إداري"],
        },
        transformation: {
          title: "تحولت الأجزاء المبعثرة إلى نظام واحد.",
          body: "أعيد تنظيم الملفات والروابط وسجلات الطلاب وإشارات الحضور حول منصة تدريب مركزية.",
        },
        after: {
          title: "مكان منظم واحد للتعلم والإدارة.",
          intro: "تمنح المنصة الطلاب مسارًا أوضح، وتمنح الإدارة رؤية تشغيلية أكثر هدوءًا.",
          points: ["حسابات للطلاب", "دورات منظمة", "تتبع الحضور", "إعلانات تشويقية للدورات", "محتوى مرتب", "إدارة أكثر وضوحًا"],
        },
        storyboard: {
          title: "رحلة تعلم ببنية مرئية واضحة.",
          intro: "تحمل الواجهة التنظيم نفسه من مدخل المنصة إلى استكشاف الدورات وتفاصيل المحتوى.",
          screenshots: [
            { src: "/assest/resize/manal-alhihi3.png", alt: "واجهة الدخول إلى منصة تدريب منال الحيحي", caption: "مدخل المنصة" },
            { src: "/assest/resize/manal-alhihi1.png", alt: "محتوى دورات منظم داخل منصة منال الحيحي", caption: "هيكلة الدورات" },
            { src: "/assest/resize/manal-alhihi.png", alt: "نظرة عامة على واجهة منصة منال الحيحي", caption: "تجربة الطالب" },
          ],
        },
        featuresTitle: "ست وحدات ضمن مسار تدريب واحد.",
        featuresIntro: "تعالج كل وحدة حاجة تشغيلية محددة، وتبقى متصلة برحلة التعلم الكاملة.",
        features: [
          { title: "حسابات الطلاب", description: "مدخل شخصي واضح لكل طالب." },
          { title: "إدارة الدورات", description: "جمع الدورات وإدارتها ضمن هيكل مرتب." },
          { title: "تتبع الحضور", description: "حالة حضور واضحة دون تخمين يدوي." },
          { title: "إعلانات الدورات", description: "معاينة مركزة قبل دخول الطالب إلى الدورة." },
          { title: "ترتيب المحتوى", description: "عرض المواد التعليمية ضمن تسلسل مقصود." },
          { title: "وضوح الإدارة", description: "رؤية أهدأ للطلاب والدورات والمتابعة." },
        ],
        result: "النتيجة لم تكن مجرد واجهة أجمل، بل تجربة تدريب أوضح وأسهل في الإدارة والمتابعة.",
        cta: "ابدأ بناء منتج رقمي واضح",
        backHome: "العودة إلى معرض الأعمال",
        chapters: ["المقدمة", "قبل", "التحول", "بعد", "المشاهد", "النظام", "النتيجة"],
      },
    },
  },
  "qasr-alfarah": {
    slug: "qasr-alfarah",
    visualTheme: "wedding-booking",
    cover: "/assest/resize/qaser-alfarah.png",
    seo: {
      title: "Qasr Al-Farah Wedding Hall Booking Case Study | قصر الفرح",
      description: "A bilingual case study about transforming paper-based wedding hall bookings into an organized booking, invitation, RSVP, and digital memory experience.",
    },
    content: {
      en: {
        eyebrow: "Wedding hall booking case study",
        title: "Qasr Al-Farah: From a paper agenda to a digital booking and memory experience",
        positioning: "Transforming the wedding hall experience from manual follow-up and repeated phone calls into a digital system that organizes bookings, invitations, and guest interaction after the event.",
        before: {
          title: "Before the system: details were scattered and pressure was daily.",
          intro: "Booking relied on a paper agenda, phone calls, and manual follow-up. Every request demanded close attention, while a delayed response could confuse a client or let an opportunity slip away.",
          points: [
            "A paper agenda that was difficult to search quickly.",
            "Repeated calls to confirm the same details.",
            "A booking could be forgotten or an interested client answered too late.",
            "Bride, groom, and event details were difficult to track.",
            "A basic website did not explain the value of the experience.",
            "Visitors could see the hall but had no clear path to book it.",
          ],
          microcopy: "When every booking hangs between paper notes and phone calls.",
        },
        transformation: {
          title: "A booking request became a connected event journey.",
          body: "Calendar blocks, event details, invitation links, RSVP responses, and guest messages settle into one operational flow.",
        },
        after: {
          title: "After the system: a clearer journey from the first visit to the last memory.",
          intro: "Booking became part of an organized digital experience. Clients understand the next step and submit a request, while the team manages details in one place. After the event, guest interaction becomes a digital book of messages and memories.",
          points: [
            "A clear booking flow for receiving requests.",
            "Event data organized instead of scattered across paper and calls.",
            "A consistent experience across phone, tablet, and laptop.",
            "Personal invitation links for the bride and groom.",
            "Clearer RSVP and guest participation.",
            "A digital memory book for messages and moments.",
          ],
          microcopy: "From exhausting manual follow-up to a booking experience the team can manage with confidence.",
        },
        storyboard: {
          title: "The journey continues beyond the booking.",
          intro: "The system connects the operational booking path with the public hall experience, responsive access, and a lasting guest-memory layer.",
          screenshots: [
            { src: "/assest/resize/qaser-alfarah3.png", presentation: "concept", alt: "Paper agenda and phone calls for wedding hall bookings before the system.", caption: "Before the system: bookings scattered between paper and phone calls." },
            { src: "/assest/resize/qaser-alfarah3.png", alt: "Digital wedding hall booking system interface.", caption: "A booking interface that clarifies the request and gathers details from the start." },
            { src: "/assest/resize/qaser-alfarah2.png", presentation: "responsive", alt: "Qasr Al-Farah website displayed on phone, tablet, and laptop.", caption: "The same experience appears clearly across phone, tablet, and laptop." },
            { src: "/assest/resize/qaser-alfarah1.png", alt: "Digital wedding memory book with guest messages for bride and groom.", caption: "A digital book that preserves guest messages and event memories." },
          ],
        },
        featuresTitle: "From booking request to guest memory.",
        featuresIntro: "Six connected modules carry the experience from operational clarity into invitation and participation.",
        features: [
          { title: "Clear Booking System", description: "A direct path for submitting and understanding booking requests." },
          { title: "Booking Dashboard", description: "One organized view for requests and event details." },
          { title: "Custom Invitations", description: "Dedicated invitation pages for the bride and groom." },
          { title: "RSVP & Guest Posts", description: "A clearer way for guests to respond and participate." },
          { title: "Digital Memory Book", description: "A lasting home for guest messages and event memories." },
          { title: "Responsive Experience", description: "The same clear journey across phone, tablet, and laptop." },
        ],
        result: "The result was not simply a better-looking interface, but a clearer experience for booking and follow-up. Clients can understand the next step, while the team has a more organized path for requests, event details, and guest interaction.",
        cta: "See how the hall moved from manual follow-up to a usable digital experience",
        backHome: "Back to portfolio",
        chapters: ["Introduction", "Before", "Booking flow", "After", "Storyboard", "System", "Result"],
      },
      ar: {
        eyebrow: "دراسة حالة لنظام حجز قاعة أفراح",
        title: "قصر الفرح: من أجندة ورقية إلى تجربة حجز وذاكرة رقمية",
        positioning: "تحويل تجربة قاعة الأفراح من متابعة يدوية ومكالمات متكررة إلى نظام رقمي ينظّم الحجز، الدعوات، وتفاعل الضيوف بعد المناسبة.",
        before: {
          title: "قبل النظام: التفاصيل موزعة والضغط يومي",
          intro: "كانت تجربة الحجز تعتمد على الأجندة الورقية، المكالمات، والمتابعة اليدوية. كل حجز يحتاج انتباهًا عاليًا، وكل تأخير بالرد قد يربك العميل أو يفتح المجال لضياع فرصة.",
          points: [
            "أجندة ورقية يصعب الرجوع لها بسرعة.",
            "مكالمات متكررة لتأكيد نفس التفاصيل.",
            "احتمال نسيان حجز أو تأخير الرد على عميل مهتم.",
            "صعوبة متابعة بيانات العريس والعروس والمناسبة.",
            "موقع بسيط لا يشرح قيمة التجربة.",
            "الزائر يرى القاعة، لكن لا يجد مسارًا واضحًا للحجز.",
          ],
          microcopy: "عندما يصبح كل حجز معلّقًا بين الورق والمكالمات.",
        },
        transformation: {
          title: "تحول طلب الحجز إلى رحلة مناسبة مترابطة.",
          body: "تنتظم مواعيد التقويم، تفاصيل المناسبة، روابط الدعوة، ردود الحضور، ورسائل الضيوف ضمن مسار تشغيلي واحد.",
        },
        after: {
          title: "بعد النظام: رحلة أوضح من أول زيارة إلى آخر ذكرى",
          intro: "أصبح الحجز جزءًا من تجربة رقمية منظمة. العميل يفهم الخطوة التالية، يرسل طلبه، والإدارة تتابع التفاصيل من مكان واحد. وبعد المناسبة، يتحول التفاعل إلى دفتر رقمي يحفظ رسائل الضيوف وذكرياتهم.",
          points: [
            "مسار حجز واضح لاستقبال طلبات الحجز.",
            "تنظيم بيانات المناسبة بدل تشتتها بين الورق والمكالمات.",
            "تجربة متوافقة مع الهاتف، التابلت، واللابتوب.",
            "روابط دعوة مخصصة للعريس والعروس.",
            "تأكيد حضور ومشاركة ضيوف بطريقة أوضح.",
            "دفتر ذكريات رقمي للرسائل والذكريات.",
          ],
          microcopy: "من متابعة يدوية مرهقة إلى تجربة حجز يمكن إدارتها بثقة.",
        },
        storyboard: {
          title: "رحلة تستمر بعد اكتمال الحجز.",
          intro: "يربط النظام بين مسار الحجز التشغيلي، حضور القاعة الرقمي، الوصول المتجاوب، وطبقة ذكريات تبقى بعد المناسبة.",
          screenshots: [
            { src: "/assest/resize/qaser-alfarah3.png", presentation: "concept", alt: "أجندة ورقية ومكالمات لحجوزات قاعة أفراح قبل النظام.", caption: "قبل النظام: حجوزات موزعة بين الورق والمكالمات." },
            { src: "/assest/resize/qaser-alfarah3.png", alt: "واجهة نظام حجز قاعة أفراح رقمية.", caption: "واجهة حجز توضّح الطلب وتجمع التفاصيل من البداية." },
            { src: "/assest/resize/qaser-alfarah2.png", presentation: "responsive", alt: "موقع قصر الفرح معروض على هاتف وتابلت ولابتوب.", caption: "نفس التجربة تظهر بوضوح على الهاتف، التابلت، واللابتوب." },
            { src: "/assest/resize/qaser-alfarah1.png", alt: "دفتر ذكريات رقمي للعريس والعروس ورسائل الضيوف.", caption: "دفتر رقمي يحفظ رسائل الضيوف وذكريات المناسبة." },
          ],
        },
        featuresTitle: "من طلب الحجز إلى ذاكرة الضيوف.",
        featuresIntro: "ست وحدات مترابطة تنقل التجربة من وضوح التشغيل إلى الدعوة والمشاركة.",
        features: [
          { title: "نظام حجز واضح", description: "مسار مباشر لإرسال طلب الحجز وفهمه." },
          { title: "لوحة إدارة للحجوزات", description: "رؤية منظمة للطلبات وتفاصيل المناسبة." },
          { title: "صفحات دعوة مخصصة", description: "صفحات دعوة خاصة للعريس والعروس." },
          { title: "تأكيد ومشاركة الضيوف", description: "طريقة أوضح لرد الضيوف ومشاركتهم." },
          { title: "دفتر ذكريات رقمي", description: "مكان دائم لرسائل الضيوف وذكريات المناسبة." },
          { title: "تجربة متجاوبة", description: "رحلة واضحة نفسها على الهاتف والتابلت واللابتوب." },
        ],
        result: "النتيجة لم تكن مجرد واجهة أجمل، بل تجربة أوضح للحجز والمتابعة. أصبح بإمكان العميل فهم الخطوة التالية، وأصبح لدى الإدارة مسار أكثر تنظيمًا للتعامل مع الطلبات، بيانات المناسبة، وتفاعل الضيوف.",
        cta: "شاهد كيف تحولت القاعة من متابعة يدوية إلى تجربة رقمية قابلة للاستخدام",
        backHome: "العودة إلى معرض الأعمال",
        chapters: ["المقدمة", "قبل", "مسار الحجز", "بعد", "المشاهد", "النظام", "النتيجة"],
      },
    },
  },
};
