export const content = {
    en: {
        nav: {
            home: "Home",
            whyUs: "Why Us?",
            services: "Expertise",
            portfolio: "Work",
            whyChange: "Why Change?",
            caseStudies: "Case Studies",
            diagnosis: "Diagnosis",
            testimonials: "Signals",
            contact: "Contact",
            cta: "Start a Build",
        },
        hero: {
            title: "Digital Product Studio",
            headline: "Digital systems that simplify your work and move you forward.",
            subheading: "We build websites, workspaces, and dashboards that turn technological complexity into a smooth experience. Our goal is to give you the clarity and confidence to make decisions and get work done with ease.",
            supportingLine: "",
            primaryCTA: "Start a focused build",
            secondaryCTA: "See the method",
        },
        about: {
            eyebrow: "An excellent fit for companies, clinics, and service providers who need stronger credibility.",
            title: "Your website is not just a page. It is the space where decisions are made.",
            summary: "Social media creates the first spark and captures attention, but when a customer looks for certainty, they come here. Your website is your digital branch that never sleeps: the place that explains your value calmly, removes hesitation, and gives visitors a clear map to the next step.",
            points: [
                "We turn attention into trust.",
                "We translate trust into a clear action.",
                "And action becomes a loyal customer for your brand.",
            ],
            cta: "Why your company needs a website",
        },
        services: {
            title: "What DOMINASE builds",
            subtitle: "Focused digital surfaces for businesses that need their offer, workflow, and customer path to feel clearer.",
            items: [
                {
                    title: "Websites that explain the offer",
                    desc: "Public pages with strong hierarchy, useful storytelling, and a clear reason to contact or continue.",
                    icon: "development",
                },
                {
                    title: "Product and dashboard interfaces",
                    desc: "Screens for admins, teams, customers, and workflows that need order instead of scattered tools.",
                    icon: "consulting",
                },
                {
                    title: "Booking, form, and workflow paths",
                    desc: "Digital paths for requests, RSVPs, surveys, checkout steps, onboarding, and follow-up.",
                    icon: "marketing",
                },
            ],
            cta: "Start a project conversation",
        },
        beneathInterface: {
            eyebrow: "Beneath the interface",
            title: "Beyond the screen.",
            intro: "DOMINASE reveals the hidden architecture that drives serious digital experiences.",
            cta: "Discuss a Project",
            scenes: [
                {
                    id: "surface",
                    index: "01",
                    label: "The Surface",
                    headline: "What your visitors see is only the beginning.",
                    body: "The final interface is the tip of the iceberg. At DOMINASE, we build the solid depth that makes that surface stable, reliable, and ready to work.",
                },
                {
                    id: "presentation",
                    index: "02",
                    label: "Presentation",
                    headline: "This is where the first and strongest impression is shaped.",
                    body: "Cinematic interfaces with a captivating visual direction and purposeful motion designed to build trust, guide the eye, and encourage the visitor to take the next step.",
                },
                {
                    id: "interaction",
                    index: "03",
                    label: "Interaction",
                    headline: "The living pulse of the experience.",
                    body: "We guide users smoothly through forms, bookings, and surveys. Every click and transition is designed to feel fast, intuitive, and comfortable for real users.",
                },
                {
                    id: "logic",
                    index: "04",
                    label: "Logic",
                    headline: "The mind behind the scenes.",
                    body: "An intelligent layer that manages data, applies validation rules, and directs workflows with strict precision. We give you a system designed to work smartly and without errors.",
                },
                {
                    id: "operations",
                    index: "05",
                    label: "Operations",
                    headline: "The control room for your business.",
                    body: "Clean, comprehensive admin panels organize requests and content, giving you clearer visibility and fuller control over the daily work happening behind the screen.",
                },
                {
                    id: "assembly",
                    index: "06",
                    label: "Operating Layer",
                    headline: "Absolute harmony between the layers.",
                    body: "All these layers merge into one digital entity from DOMINASE: an operating system designed specifically to turn attention into real action.",
                },
            ],
        },
        portfolio: {
            title: "Work built around real business friction.",
            subtitle: "Each project starts with a specific kind of confusion: bookings handled through repeated calls, training spread across links, care requests that need reassurance, or surveys that need structure.",
            projectCTA: "View case study",
            items: [
                {
                    title: "Qasr Al-Farah",
                    category: "Wedding Hall Operating Platform",
                    desc: "A wedding-hall experience shaped around public presentation, booking requests, event details, invitations, RSVP, and guest memory moments.",
                    image: "/assest/resize/qaser-alfarah.png",
                    link: "#",
                    slug: "qasr-al-farah",
                },
                {
                    title: "Curevie",
                    category: "Healthcare Digital Experience",
                    desc: "A healthcare-oriented digital presence shaped to explain services clearly and make the first contact feel more reassuring.",
                    image: "/assest/curevie3.jpeg",
                    link: "#",
                    slug: "curevie",
                },
                {
                    title: "Horvath Survey",
                    category: "Survey & Business Data Platform",
                    desc: "A structured survey and data-capture experience focused on readable questions, clean forms, and clearer assessment output.",
                    image: "/assest/resize/horvath1.jpg",
                    link: "#",
                    slug: "horvath-survey",
                },
                {
                    title: "Manal Alhihi Educational Platform",
                    category: "Educational Platform",
                    desc: "A training platform direction built around organized courses, student access, attendance signals, and clearer learning content.",
                    image: "/assest/resize/manal-alhihi.png",
                    link: "#",
                    slug: "manal-alhihi",
                },
            ],
            cta: "Open the case studies",
        },
        testimonials: {
            title: "What success partners say after the experience.",
            subtitle: "Testimonials from real projects reflecting the impact of the experience after the build.",
            items: [
                {
                    quote: "I never imagined that a system of this size could work this smoothly. Mohammed Aldomi did not build just a website for Curevie; he designed a complete medical ecosystem. From the patient interface that allows people to request a doctor or lab service at home with one click, to the provider app for instant communication and accurate medical file attachments, all the way to the comprehensive admin dashboard that keeps the entire rhythm under control. The digital experience Dominase delivered moved our service to a completely new level of reliability and speed, while preserving the human touch we care about in patient care. Exceptional work by every measure.",
                    author: "Dr. Ahmad Al-Akhras",
                    role: "Director, Curevie",
                },
                {
                    quote: "Working with Dominase was pure creativity. Mohammed Aldomi understood our vision for Inkspire from the first moment and turned our portfolio into a captivating cinematic experience. Every motion on the site, every timed transition, and every visual detail was executed with eye-catching precision. He did not design just a website for us; he created a sharp and practical artistic piece that impresses our clients and highlights the strength of our marketing campaigns as soon as they enter the page. The collaboration was comfortable and professional, and the final result exceeded all my expectations.",
                    author: "Sultan Al-Hajj",
                    role: "Director, Inkspire",
                },
                {
                    quote: "A real qualitative shift in the way we manage our work. What Mohammed Aldomi delivered was not just an impressive interface to showcase our engineering projects; it was an integrated system that reorganized the way we operate. From smoothly managing client appointments, to organizing project details, tracking employees, and following payments in one precise and structured place. The remarkable attention to detail and the clear explanation of every step during the build gave us both visual and operational confidence, raising the value of our company and its image in front of our clients. Dominase is a true partner in success and professionalism.",
                    author: "Eng. Ahmad Khaled",
                    role: "Owner, Engineering Company",
                },
            ],
            cta: "Start a project conversation",
        },
        contact: {
            title: "Tell me what needs to become clearer.",
            subtitle: "Share the business, the current digital friction, and the result you want the interface to support.",
            info: {
                phone: "+962779667168",
                email: "mohammed.aldomi68@gmail.com",
                address: "Amman, Jordan",
            },
            form: {
                name: "Name",
                email: "Email",
                phone: "Phone Number",
                message: "What should the website or product help people do?",
                submit: "Send the project context",
            },
            portal: {
                eyebrow: "Project context",
                panelLabel: "Useful starting point",
                fields: {
                    name: { label: "Name", placeholder: "Your full name" },
                    phone: { label: "Phone number", placeholder: "Best number to reach you" },
                    company: { label: "Company", placeholder: "Company (optional)" },
                },
                submit: "Send the project context",
                submitting: "Sending...",
                errors: {
                    name: "Please enter your name.",
                    phone: "Please enter a phone number.",
                    submit: "Something did not send. Try again, or use the direct contact options below.",
                    config: "Contact form is not configured. Set NEXT_PUBLIC_FORMSPREE_ENDPOINT.",
                },
                success: {
                    eyebrow: "Message received",
                    title: "Your message was sent",
                    body: "Mohammed will review the context and reply with the next useful step.",
                    button: "Send another message",
                },
                channels: {
                    heading: "Direct routes",
                    whatsapp: { label: "Message on WhatsApp", caption: "WhatsApp", helper: "Fastest reply" },
                    phone: { label: "Call by phone", caption: "Call", helper: "Talk directly" },
                    email: { label: "Send an email", caption: "Email", helper: "Formal details" },
                },
            },
        },
        features: [
            {
                title: "Product Thinking",
                desc: "Every section, screen, and interaction is shaped around what the business needs users to understand or do next.",
            },
            {
                title: "Frontend Precision",
                desc: "Responsive layouts, polished motion, clean hierarchy, and performance-aware implementation across modern interfaces.",
            },
            {
                title: "Business Workflows",
                desc: "Practical systems for bookings, dashboards, surveys, education, healthcare, checkout, and content operations.",
            },
        ],
        problem: {
            title: "Generic Websites Do Not Create Product Confidence",
            description: "Most business sites look presentable but fail to explain the offer, guide the user, or support real operations. The result is a digital presence that feels disconnected from the business behind it.",
        },
        socialProof: {
            trustedBy: "Built around real project surfaces",
            testimonial: "\"A strong digital product should feel premium on the surface and practical underneath.\"",
            attribution: "- Mohammed Aldomi, Founder",
        },
        solution: {
            title: "A Studio Built Around Working Digital Systems",
            benefits: [
                {
                    title: "Clear Presentation",
                    desc: "Premium pages that make the offer, story, and action path obvious.",
                },
                {
                    title: "Operational Depth",
                    desc: "Interfaces for dashboards, bookings, forms, and business workflows.",
                },
                {
                    title: "Polished Experience",
                    desc: "Motion, spacing, imagery, and responsive behavior tuned to feel sharp and intentional.",
                },
            ],
        },
        finalCTA: {
            title: "Does your digital presence feel smaller than the business behind it?",
            subtext: "Bring the offer, the workflow, and the points where customers hesitate. DOMINASE will help shape them into a clearer digital experience.",
            primaryCTA: "Start a project conversation",
            secondaryCTA: "View the work",
            reassurance: "Best fit for focused websites, booking paths, product interfaces, and operational screens.",
        },
        footer: {
            tagline: "DOMINASE — Digital Product Studio by Mohammed Aldomi.",
            rights: "© 2026 DOMINASE. Built by Mohammed Aldomi.",
            links: ["Portfolio", "Contact"],
        },
    },
    ar: {
        nav: {
            home: "الرئيسية",
            whyUs: "لماذا نحن؟",
            services: "الخبرات",
            portfolio: "الأعمال",
            whyChange: "لماذا التغيير؟",
            caseStudies: "دراسات الحالة",
            diagnosis: "التشخيص",
            testimonials: "إشارات الثقة",
            contact: "تواصل",
            cta: "ابدأ مشروعك",
        },
        hero: {
            title: "استوديو منتجات رقمية",
            headline: "أنظمة رقمية تُسهّل عملك، وتدفعك للأمام.",
            subheading: "نبني مواقع، مساحات عمل، ولوحات تحكم تحوّل التعقيد التكنولوجي إلى تجربة سلسة. هدفنا؟ أن نمنحك الوضوح التام والثقة لتتخذ قراراتك وتنجز مهامك براحة.",
            supportingLine: "",
            primaryCTA: "ابدأ بناءً مركزاً",
            secondaryCTA: "شاهد المنهجية",
        },
        about: {
            eyebrow: "خيار ممتاز للشركات، العيادات، أو مقدمي الخدمات الذين يبحثون عن المصداقية.",
            title: "موقعك ليس مجرد صفحة.. إنه المساحة التي يُصنع فيها القرار.",
            summary: "السوشيال ميديا تخلق الشرارة الأولى وتلفت الانتباه، لكن عندما يبحث العميل عن اليقين، فإنه يتجه إليك هنا. موقعك هو فرعك الرقمي الذي لا ينام؛ المكان الذي يشرح قيمتك بهدوء، يبدد التردد، ويمنح زوارك الخريطة الواضحة للخطوة التالية.",
            points: [
                "نستثمر الانتباه لنبني الثقة.",
                "ونُترجم الثقة إلى إجراء واضح.",
                "ليتحول الإجراء إلى عميل مخلص لعلامتك.",
            ],
            cta: "لماذا تحتاج شركتك إلى موقع؟",
        },
        services: {
            title: "ماذا تبني DOMINASE",
            subtitle: "واجهات رقمية مركزة للأعمال التي تحتاج أن يصبح عرضها ومسار عملائها وتشغيلها أوضح.",
            items: [
                {
                    title: "مواقع تشرح العرض",
                    desc: "صفحات عامة بتسلسل واضح، سرد مفيد، وسبب مباشر للتواصل أو المتابعة.",
                    icon: "development",
                },
                {
                    title: "واجهات منتجات ولوحات تحكم",
                    desc: "شاشات للإدارة، الفرق، العملاء، وسير العمل الذي يحتاج تنظيماً بدلاً من أدوات متفرقة.",
                    icon: "consulting",
                },
                {
                    title: "مسارات حجز ونماذج وتشغيل",
                    desc: "مسارات رقمية للطلبات، RSVP، الاستبيانات، خطوات الدفع، الإدخال، والمتابعة.",
                    icon: "marketing",
                },
            ],
            cta: "ابدأ محادثة مشروع",
        },
        beneathInterface: {
            eyebrow: "خلف الواجهة",
            title: "ما وراء الشاشة.",
            intro: "يكشف DOMINASE عن المعمارية الخفية التي تقود التجارب الرقمية الجادة.",
            cta: "ناقش مشروعك",
            scenes: [
                {
                    id: "surface",
                    index: "01",
                    label: "السطح",
                    headline: "ما يراه زوارك هو مجرد البداية.",
                    body: "الواجهة النهائية هي قمة الجبل الجليدي، وفي DOMINASE، نحن نبني العمق الصلب الذي يجعل هذا السطح ثابتاً وجاهزاً للعمل.",
                },
                {
                    id: "presentation",
                    index: "02",
                    label: "العرض",
                    headline: "هنا نصنع الانطباع الأول والأقوى.",
                    body: "واجهات سينمائية بتوجه بصري آسر، وحركة هادفة مصممة خصيصاً لبناء الثقة، توجيه العين، وتحفيز الزائر على اتخاذ الخطوة التالية.",
                },
                {
                    id: "interaction",
                    index: "03",
                    label: "التفاعل",
                    headline: "النبض الحي للتجربة.",
                    body: "نوجه المستخدم بسلاسة متناهية عبر النماذج، الحجوزات، والاستبيانات. كل نقرة وكل انتقال مصمم ليكون سريعاً، بديهياً، ومريحاً للمستخدمين الحقيقيين.",
                },
                {
                    id: "logic",
                    index: "04",
                    label: "المنطق",
                    headline: "العقل المدبر خلف الكواليس.",
                    body: "طبقة ذكية تدير البيانات، تطبق قواعد التحقق، وتوجه مسارات العمل بدقة صارمة. نحن نضمن لك نظاماً يعمل بذكاء وبلا أخطاء.",
                },
                {
                    id: "operations",
                    index: "05",
                    label: "العمليات",
                    headline: "غرفة التحكم الخاصة بعملك.",
                    body: "لوحات إدارة شاملة ونظيفة تنظم الطلبات والمحتوى، لتمنحك رؤية واضحة وتحكماً كاملاً يسهّل إدارة أعمالك اليومية خلف الشاشة.",
                },
                {
                    id: "assembly",
                    index: "06",
                    label: "النظام الشامل",
                    headline: "التناغم المطلق.",
                    body: "تندمج كل هذه الطبقات في كيان رقمي واحد من DOMINASE؛ نظام تشغيل صُمم خصيصاً ليحول الانتباه إلى إجراء حقيقي.",
                },
            ],
        },
        portfolio: {
            title: "أعمال مبنية حول احتكاك حقيقي في العمل.",
            subtitle: "يبدأ كل مشروع من نوع محدد من الارتباك: حجوزات تُدار بمكالمات متكررة، تدريب موزع بين روابط، طلبات رعاية تحتاج طمأنة، أو استبيانات تحتاج هيكلاً واضحاً.",
            projectCTA: "عرض دراسة الحالة",
            items: [
                {
                    title: "Qasr Al-Farah",
                    category: "منصة تشغيل لقاعات الأفراح",
                    desc: "تجربة قاعة أفراح مبنية حول العرض العام، طلبات الحجز، تفاصيل المناسبة، الدعوات، RSVP، ولحظات ذكريات الضيوف.",
                    image: "/assest/resize/qaser-alfarah.png",
                    link: "#",
                    slug: "qasr-al-farah",
                },
                {
                    title: "Curevie",
                    category: "تجربة رقمية طبية",
                    desc: "حضور رقمي في المجال الصحي يساعد على شرح الخدمات بوضوح ويجعل التواصل الأول أكثر طمأنينة.",
                    image: "/assest/curevie3.jpeg",
                    link: "#",
                    slug: "curevie",
                },
                {
                    title: "Horvath Survey",
                    category: "منصة استبيانات وبيانات أعمال",
                    desc: "تجربة استبيانات وجمع بيانات تركز على أسئلة مقروءة، نماذج نظيفة، ومخرجات تقييم أوضح.",
                    image: "/assest/resize/horvath1.jpg",
                    link: "#",
                    slug: "horvath-survey",
                },
                {
                    title: "Manal Alhihi Educational Platform",
                    category: "منصة تعليمية",
                    desc: "اتجاه منصة تدريب مبني حول دورات منظمة، وصول الطلاب، إشارات الحضور، ومحتوى تعليمي أوضح.",
                    image: "/assest/resize/manal-alhihi.png",
                    link: "#",
                    slug: "manal-alhihi",
                },
            ],
            cta: "افتح دراسات الحالة",
        },
        testimonials: {
            title: "ما يقوله شركاء النجاح بعد التجربة.",
            subtitle: "شهادات من مشاريع حقيقية عكست أثر التجربة بعد البناء.",
            items: [
                {
                    quote: "لم أكن أتخيل أن نظاماً بهذا الحجم يمكن أن يعمل بهذه السلاسة! محمد الدومي لم يبنِ مجرد موقع لـ Curevie، بل صمم منظومة طبية متكاملة. من واجهة المريض التي تتيح طلب الطبيب والمختبر للمنزل بضغطة زر، إلى التطبيق الخاص بمقدمي الخدمة للتواصل الفوري وإرفاق الملفات الطبية بدقة، وصولاً إلى لوحة الإدارة الشاملة التي تضبط كل هذا الإيقاع. التجربة الرقمية التي قدمها لنا Dominase نقلت خدمتنا لمستوى آخر تماماً من الموثوقية والسرعة، مع الحفاظ على اللمسة الإنسانية التي نحرص عليها في رعاية مرضانا. عمل استثنائي بكل المقاييس!",
                    author: "الدكتور أحمد الأخرس",
                    role: "مدير شركة Curevie",
                },
                {
                    quote: "العمل مع Dominase كان إبداعاً خالصاً! محمد الدومي فهم رؤيتنا لـ Inkspire من اللحظة الأولى، وحوّل معرض أعمالنا إلى تجربة سينمائية ساحرة. كل حركة في الموقع، كل انتقال زمني، وكل تفصيل بصري تم تنفيذه بدقة متناهية تخطف العين. لم يصمم لنا مجرد موقع، بل صنع تحفة فنية حادة وعملية تبهر عملاءنا وتبرز قوة حملاتنا التسويقية بمجرد دخولهم للصفحة. التعامل كان مريحاً واحترافياً، والنتيجة النهائية فاقت كل توقعاتي!",
                    author: "سلطان الحاج",
                    role: "مدير شركة Inkspire",
                },
                {
                    quote: "نقلة نوعية حقيقية في طريقة إدارتنا للعمل! ما قدمه محمد الدومي لم يكن مجرد واجهة مبهرة لعرض مشاريعنا الهندسية، بل نظاماً متكاملاً أعاد ترتيب أوراقنا بالكامل. من تنظيم مواعيد العملاء بسلاسة، إلى إدارة تفاصيل المشاريع، ومتابعة الموظفين والدفعات في مكان واحد دقيق ومنظم. الاهتمام المذهل بالتفاصيل، والشرح الواضح لكل خطوة خلال فترة البناء، منحنا ثقة بصرية وعملية رفعت من قيمة شركتنا وصورتها أمام عملائنا. Dominase شريك حقيقي للنجاح والاحترافية!",
                    author: "المهندس أحمد خالد",
                    role: "صاحب شركة هندسية",
                },
            ],
            cta: "ابدأ محادثة مشروع",
        },
        contact: {
            title: "أخبرني ما الذي يحتاج أن يصبح أوضح.",
            subtitle: "شارك طبيعة العمل، الاحتكاك الرقمي الحالي، والنتيجة التي تريد من الواجهة أن تدعمها.",
            info: {
                phone: "+962779667168",
                email: "mohammed.aldomi68@gmail.com",
                address: "عمّان، الأردن",
            },
            form: {
                name: "الاسم",
                email: "البريد الإلكتروني",
                phone: "رقم الهاتف",
                message: "ماذا يجب أن يساعد الموقع أو المنتج الناس على فعله؟",
                submit: "أرسل سياق المشروع",
            },
            portal: {
                eyebrow: "سياق المشروع",
                panelLabel: "نقطة بداية مفيدة",
                fields: {
                    name: { label: "الاسم", placeholder: "اسمك الكامل" },
                    phone: { label: "رقم الهاتف", placeholder: "أفضل رقم للتواصل معك" },
                    company: { label: "اسم الشركة", placeholder: "اسم الشركة (اختياري)" },
                },
                submit: "أرسل سياق المشروع",
                submitting: "جارٍ الإرسال...",
                errors: {
                    name: "الرجاء إدخال اسمك.",
                    phone: "الرجاء إدخال رقم الهاتف.",
                    submit: "لم يتم الإرسال. حاول مرة أخرى، أو استخدم طرق التواصل المباشرة بالأسفل.",
                    config: "نموذج التواصل غير مهيأ. الرجاء ضبط NEXT_PUBLIC_FORMSPREE_ENDPOINT.",
                },
                success: {
                    eyebrow: "تم استلام الرسالة",
                    title: "تم إرسال رسالتك",
                    body: "سيراجع Mohammed السياق ويرد عليك بالخطوة التالية المفيدة.",
                    button: "إرسال رسالة أخرى",
                },
                channels: {
                    heading: "مسارات مباشرة",
                    whatsapp: { label: "راسلني على واتساب", caption: "واتساب", helper: "رد أسرع" },
                    phone: { label: "اتصل بي هاتفياً", caption: "اتصال", helper: "تواصل مباشر" },
                    email: { label: "أرسل بريداً إلكترونياً", caption: "بريد", helper: "تفاصيل رسمية" },
                },
            },
        },
        features: [
            {
                title: "تفكير منتج",
                desc: "كل قسم وشاشة وتفاعل يتم بناؤه حول ما يحتاج المستخدم أن يفهمه أو يفعله بعد ذلك.",
            },
            {
                title: "دقة في الواجهة",
                desc: "تخطيطات متجاوبة، حركة مصقولة، تسلسل بصري واضح، وتنفيذ واعٍ بالأداء عبر واجهات حديثة.",
            },
            {
                title: "سير عمل للأعمال",
                desc: "أنظمة عملية للحجز، لوحات التحكم، الاستبيانات، التعليم، الصحة، الدفع، وتشغيل المحتوى.",
            },
        ],
        problem: {
            title: "المواقع العامة لا تبني ثقة المنتج",
            description: "معظم مواقع الأعمال تبدو مقبولة لكنها لا تشرح العرض، لا توجه المستخدم، ولا تدعم العمليات الحقيقية. النتيجة حضور رقمي منفصل عن قيمة العمل نفسه.",
        },
        socialProof: {
            trustedBy: "مبني حول واجهات مشاريع حقيقية",
            testimonial: "\"المنتج الرقمي القوي يجب أن يبدو فاخراً على السطح وعملياً في الداخل.\"",
            attribution: "- Mohammed Aldomi، المؤسس",
        },
        solution: {
            title: "استوديو مبني حول أنظمة رقمية تعمل",
            benefits: [
                {
                    title: "عرض واضح",
                    desc: "صفحات فاخرة تجعل العرض والقصة ومسار الإجراء واضحين.",
                },
                {
                    title: "عمق تشغيلي",
                    desc: "واجهات للوحات التحكم، الحجوزات، النماذج، وسير عمل الشركات.",
                },
                {
                    title: "تجربة مصقولة",
                    desc: "حركة، مسافات، صور، وسلوك متجاوب مضبوط ليبدو حاداً ومقصوداً.",
                },
            ],
        },
        finalCTA: {
            title: "هل يبدو حضورك الرقمي أصغر من العمل الذي يقف خلفه؟",
            subtext: "أحضر العرض، مسار العمل، والنقاط التي يتردد عندها العملاء. ستساعدك DOMINASE في تحويلها إلى تجربة رقمية أوضح.",
            primaryCTA: "ابدأ محادثة مشروع",
            secondaryCTA: "شاهد الأعمال",
            reassurance: "مناسب للمواقع المركزة، مسارات الحجز، واجهات المنتجات، والشاشات التشغيلية.",
        },
        footer: {
            tagline: "DOMINASE — Digital Product Studio by Mohammed Aldomi.",
            rights: "© 2026 DOMINASE. Built by Mohammed Aldomi.",
            links: ["الأعمال", "تواصل"],
        },
    },
};
