export const content = {
    en: {
        nav: {
            home: "Home",
            whyUs: "Why Us?",
            services: "Expertise",
            portfolio: "Work",
            whyChange: "Why Change?",
            caseStudies: "Case Studies",
            testimonials: "Signals",
            contact: "Contact",
            cta: "Start a Build",
        },
        hero: {
            title: "DIGITAL PRODUCT STUDIO",
            headline: "Digital systems built to move business.",
            subheading: "We design websites, dashboards, and product experiences that turn complexity into trust, clarity, and action.",
            supportingLine: "",
            primaryCTA: "Start the build",
            secondaryCTA: "View the method",
        },
        about: {
            eyebrow: "Why the website matters",
            title: "A website is not a page. It is the decision point.",
            summary: "Customers may discover you on social media, but they decide when they find a place that explains your offer, builds trust, and gives them a clear next step.",
            points: [
                "Turn attention into trust",
                "Turn trust into action",
                "Turn action into a customer",
            ],
            cta: "Why your company needs a website",
        },
        services: {
            title: "What DOMINASE Builds",
            subtitle: "Cinematic presentation, business logic, and polished frontend execution shaped as one studio process.",
            items: [
                {
                    title: "Cinematic Websites",
                    desc: "Premium marketing websites with strong visual direction, precise responsive layouts, purposeful motion, and conversion-aware sections.",
                    icon: "development",
                },
                {
                    title: "SaaS & Dashboard Interfaces",
                    desc: "Clean operational screens for admin panels, booking management, content flows, data capture, and business workflows.",
                    icon: "consulting",
                },
                {
                    title: "Product Flows",
                    desc: "Booking, checkout, surveys, RSVP, education, and onboarding flows designed to feel clear, fast, and reliable for real users.",
                    icon: "marketing",
                },
            ],
            cta: "Discuss a Project",
        },
        beneathInterface: {
            eyebrow: "BUILD SYSTEM",
            title: "Beneath the Interface",
            intro: "DOMINASE reveals the system behind a serious digital experience.",
            cta: "Discuss a Project",
            scenes: [
                {
                    id: "surface",
                    index: "01",
                    label: "Surface",
                    headline: "A website is only the surface.",
                    body: "Most visitors see the finished interface. DOMINASE builds what makes it work.",
                },
                {
                    id: "presentation",
                    index: "02",
                    label: "Presentation",
                    headline: "The visible layer explains the business, shapes perception, and builds trust.",
                    body: "Cinematic marketing pages with strong visual direction, conversion-aware structure, and purposeful motion.",
                },
                {
                    id: "interaction",
                    index: "03",
                    label: "Interaction",
                    headline: "The flow layer guides people through forms, bookings, surveys, RSVP, and next steps.",
                    body: "Every step designed to feel clear, fast, and reliable for real users.",
                },
                {
                    id: "logic",
                    index: "04",
                    label: "Logic",
                    headline: "The logic layer handles rules, validation, data capture, and business paths.",
                    body: "Conditional flows, form intelligence, and routing that makes the experience trustworthy.",
                },
                {
                    id: "operations",
                    index: "05",
                    label: "Operations",
                    headline: "The operations layer organizes requests, bookings, content, and admin workflows.",
                    body: "Clean dashboards and admin screens so the business runs clearly behind the scenes.",
                },
                {
                    id: "assembly",
                    index: "06",
                    label: "Operating Layer",
                    headline: "One connected system built to turn attention into action.",
                    body: "All four layers — assembled into a single DOMINASE digital operating layer.",
                },
            ],
        },
        portfolio: {
            title: "Selected Product Work",
            subtitle: "Real interface systems spanning booking platforms, healthcare experiences, surveys, education, dashboards, and conversion-focused presentation.",
            projectCTA: "View Project",
            items: [
                {
                    title: "Qasr Al-Farah",
                    category: "Wedding Hall Operating Platform",
                    desc: "A full wedding-hall digital platform combining a premium public website, booking flow, checkout, admin dashboard, digital invitations, RSVP, guest photo uploads, and memory-book experiences.",
                    image: "/assest/resize/qaser-alfarah.png",
                    link: "#",
                    slug: "qasr-al-farah",
                },
                {
                    title: "Curevie",
                    category: "Healthcare Digital Experience",
                    desc: "A healthcare-oriented digital experience shaped around trust, clarity, clean presentation, and a polished medical-grade interface.",
                    image: "/assest/curevie3.jpeg",
                    link: "#",
                    slug: "curevie",
                },
                {
                    title: "Horvath Survey",
                    category: "Survey & Business Data Platform",
                    desc: "A structured survey and data-capture experience focused on readable flows, clean forms, and practical business insight.",
                    image: "/assest/resize/horvath1.jpg",
                    link: "#",
                    slug: "horvath-survey",
                },
                {
                    title: "Manal Alhihi Educational Platform",
                    category: "Educational Platform",
                    desc: "An educational platform concept built around organized learning content, clear navigation, and a professional student-facing experience.",
                    image: "/assest/resize/manal-alhihi.png",
                    link: "#",
                    slug: "manal-alhihi",
                },
            ],
            cta: "See More on GitHub",
        },
        testimonials: {
            title: "Proof Signals",
            subtitle: "The studio is built around practical product surfaces, not placeholder praise.",
            items: [
                {
                    quote: "Mohammed brought a calm, organized way of thinking to our digital presence. The Curevie experience feels clear, trusted, and polished without losing the human side we care about.",
                    author: "Dr. Ahmad Al-Akhras",
                    role: "Director, Curevie",
                },
                {
                    quote: "Working with Dominase felt easy and professional from the first conversation. Mohammed understood the brand direction quickly and turned the idea into an interface that feels sharp, practical, and ready for real users.",
                    author: "Sultan Al-Hajj",
                    role: "Director, Inkspire",
                },
                {
                    quote: "The final result had the kind of structure and visual confidence we needed. Mohammed paid attention to the small details, explained the choices clearly, and delivered work that genuinely elevated our company image.",
                    author: "Eng. Ahmad Khaled",
                    role: "Owner, Engineering Company",
                },
            ],
            cta: "Start a Serious Build",
        },
        contact: {
            title: "Let's Build Something Useful",
            subtitle: "Send a message if your business needs a polished website, a SaaS-style interface, a booking flow, or a sharper digital system.",
            info: {
                phone: "+962779667168",
                email: "mohammed.aldomi68@gmail.com",
                address: "Amman, Jordan",
            },
            form: {
                name: "Name",
                email: "Email",
                phone: "Phone Number",
                message: "Project Details",
                submit: "Send Message",
            },
            portal: {
                eyebrow: "The decision point",
                panelLabel: "Signal capture",
                fields: {
                    name: { label: "Name", placeholder: "Your full name" },
                    phone: { label: "Phone number", placeholder: "Best number to reach you" },
                    company: { label: "Company", placeholder: "Company (optional)" },
                },
                submit: "Start the conversation",
                submitting: "Sending…",
                errors: {
                    name: "Please enter your name.",
                    phone: "Please enter a phone number.",
                    submit: "Something went wrong. Please try again, or reach me directly below.",
                    config: "Contact form is not configured. Set NEXT_PUBLIC_FORMSPREE_ENDPOINT.",
                },
                success: {
                    eyebrow: "Signal received",
                    title: "Your request was sent",
                    body: "You just took the first step toward changing how your project shows up to the world. Mohammed will review the details and get back to you soon.",
                    button: "Send another message",
                },
                channels: {
                    heading: "Direct routes",
                    whatsapp: { label: "Message on WhatsApp", caption: "WhatsApp", helper: "Fastest reply" },
                    phone: { label: "Call by phone", caption: "Call", helper: "Talk directly" },
                    email: { label: "Send an email", caption: "Email", helper: "Formal details" },
                },
            },
        },
        features: [
            {
                title: "Product Thinking",
                desc: "Every section, screen, and interaction is shaped around what the business needs users to understand or do next.",
            },
            {
                title: "Frontend Precision",
                desc: "Responsive layouts, polished motion, clean hierarchy, and performance-aware implementation across modern interfaces.",
            },
            {
                title: "Business Workflows",
                desc: "Practical systems for bookings, dashboards, surveys, education, healthcare, checkout, and content operations.",
            },
        ],
        problem: {
            title: "Generic Websites Do Not Create Product Confidence",
            description: "Most business sites look presentable but fail to explain the offer, guide the user, or support real operations. The result is a digital presence that feels disconnected from the business behind it.",
        },
        socialProof: {
            trustedBy: "Built around real project surfaces",
            testimonial: "\"A strong digital product should feel premium on the surface and practical underneath.\"",
            attribution: "- Mohammed Aldomi, Founder",
        },
        solution: {
            title: "A Studio Built Around Working Digital Systems",
            benefits: [
                {
                    title: "Clear Presentation",
                    desc: "Premium pages that make the offer, story, and action path obvious.",
                },
                {
                    title: "Operational Depth",
                    desc: "Interfaces for dashboards, bookings, forms, and business workflows.",
                },
                {
                    title: "Polished Experience",
                    desc: "Motion, spacing, imagery, and responsive behavior tuned to feel sharp and intentional.",
                },
            ],
        },
        finalCTA: {
            title: "Ready to Build a Sharper Digital Product?",
            subtext: "Bring the project, the business context, and the ambition. DOMINASE will help turn it into a polished interface people can trust.",
            primaryCTA: "Start a Build",
            secondaryCTA: "View the Work",
            reassurance: "Available for focused websites, product interfaces, and operational systems.",
        },
        footer: {
            tagline: "DOMINASE — Digital Product Studio by Mohammed Aldomi.",
            rights: "© 2026 DOMINASE. Built by Mohammed Aldomi.",
            links: ["Portfolio", "Contact"],
        },
    },
    ar: {
        nav: {
            home: "الرئيسية",
            whyUs: "لماذا نحن؟",
            services: "الخبرات",
            portfolio: "الأعمال",
            whyChange: "لماذا التغيير؟",
            caseStudies: "دراسات الحالة",
            testimonials: "إشارات الثقة",
            contact: "تواصل",
            cta: "ابدأ مشروعك",
        },
        hero: {
            title: "\u0627\u0633\u062a\u0648\u062f\u064a\u0648 \u0645\u0646\u062a\u062c\u0627\u062a \u0631\u0642\u0645\u064a\u0629",
            headline: "\u0623\u0646\u0638\u0645\u0629 \u0631\u0642\u0645\u064a\u0629 \u062a\u064f\u062d\u0631\u0651\u0643 \u0627\u0644\u0639\u0645\u0644 \u0628\u0648\u0636\u0648\u062d.",
            subheading: "\u0646\u0628\u0646\u064a \u0645\u0648\u0627\u0642\u0639\u060c \u0644\u0648\u062d\u0627\u062a \u062a\u062d\u0643\u0645\u060c \u0648\u062a\u062c\u0627\u0631\u0628 \u0631\u0642\u0645\u064a\u0629 \u062a\u062d\u0648\u0651\u0644 \u0627\u0644\u062a\u0639\u0642\u064a\u062f \u0625\u0644\u0649 \u062b\u0642\u0629\u060c \u0648\u0636\u0648\u062d\u060c \u0648\u0641\u0639\u0644.",
            supportingLine: "",
            primaryCTA: "\u0627\u0628\u062f\u0623 \u0627\u0644\u0628\u0646\u0627\u0621",
            secondaryCTA: "\u0634\u0627\u0647\u062f \u0627\u0644\u0645\u0646\u0647\u062c\u064a\u0629",
        },
        about: {
            eyebrow: "لماذا الموقع مهم؟",
            title: "الموقع ليس صفحة. إنه نقطة القرار.",
            summary: "قد يكتشفك العميل من السوشال ميديا، لكنه يقرر عندما يجد مكانًا واضحًا يشرح عرضك، يبني الثقة، ويعطيه الخطوة التالية.",
            points: [
                "يحوّل الانتباه إلى ثقة",
                "يحوّل الثقة إلى إجراء",
                "يحوّل الإجراء إلى عميل",
            ],
            cta: "لماذا تحتاج شركتك إلى موقع؟",
        },
        services: {
            title: "ماذا تبني DOMINASE",
            subtitle: "عرض سينمائي، منطق أعمال، وتنفيذ واجهات مصقول ضمن عملية استوديو واحدة.",
            items: [
                {
                    title: "مواقع سينمائية",
                    desc: "مواقع تسويقية فاخرة بتوجه بصري قوي، تخطيطات متجاوبة دقيقة، حركة هادفة، وأقسام مصممة للتحويل.",
                    icon: "development",
                },
                {
                    title: "واجهات SaaS ولوحات تحكم",
                    desc: "شاشات تشغيلية نظيفة للوحات الإدارة، إدارة الحجوزات، مسارات المحتوى، جمع البيانات، وسير عمل الشركات.",
                    icon: "consulting",
                },
                {
                    title: "مسارات المنتجات",
                    desc: "حجز، دفع، استبيانات، RSVP، تعليم، وتجارب إدخال مصممة لتكون واضحة وسريعة وموثوقة للمستخدمين.",
                    icon: "marketing",
                },
            ],
            cta: "ناقش مشروعك",
        },
        beneathInterface: {
            eyebrow: "BUILD SYSTEM",
            title: "خلف الواجهة",
            intro: "يكشف DOMINASE النظام الذي يقف خلف التجربة الرقمية الجادة.",
            cta: "ناقش مشروعك",
            scenes: [
                {
                    id: "surface",
                    index: "01",
                    label: "السطح",
                    headline: "الموقع هو الطبقة الظاهرة فقط.",
                    body: "معظم الزوار يرون الواجهة النهائية. DOMINASE يبني ما يجعلها تعمل.",
                },
                {
                    id: "presentation",
                    index: "02",
                    label: "Presentation",
                    headline: "الطبقة الظاهرة تشرح العمل، تشكّل الانطباع، وتبني الثقة.",
                    body: "صفحات تسويقية سينمائية بتوجه بصري قوي، هيكل موجه للتحويل، وحركة هادفة.",
                },
                {
                    id: "interaction",
                    index: "03",
                    label: "Interaction",
                    headline: "طبقة التفاعل توجه المستخدم عبر النماذج، الحجوزات، الاستبيانات، RSVP، والخطوة التالية.",
                    body: "كل خطوة مصممة لتكون واضحة وسريعة وموثوقة للمستخدمين الحقيقيين.",
                },
                {
                    id: "logic",
                    index: "04",
                    label: "Logic",
                    headline: "طبقة المنطق تدير القواعد، التحقق، جمع البيانات، ومسارات العمل.",
                    body: "مسارات شرطية، ذكاء النماذج، وتوجيه البيانات الذي يجعل التجربة موثوقة.",
                },
                {
                    id: "operations",
                    index: "05",
                    label: "Operations",
                    headline: "طبقة التشغيل تنظم الطلبات، الحجوزات، المحتوى، ولوحات الإدارة.",
                    body: "لوحات تحكم نظيفة وشاشات إدارة حتى يعمل العمل بوضوح خلف الشاشة.",
                },
                {
                    id: "assembly",
                    index: "06",
                    label: "Operating Layer",
                    headline: "نظام واحد متصل مبني لتحويل الانتباه إلى إجراء.",
                    body: "جميع الطبقات الأربع — مجمّعة في طبقة تشغيل رقمية واحدة من DOMINASE.",
                },
            ],
        },
        portfolio: {
            title: "أعمال مختارة",
            subtitle: "أنظمة واجهات حقيقية تشمل منصات حجز، تجارب صحية، استبيانات، تعليم، لوحات تحكم، وعرض تسويقي موجه للتحويل.",
            projectCTA: "عرض المشروع",
            items: [
                {
                    title: "Qasr Al-Farah",
                    category: "منصة تشغيل لقاعات الأفراح",
                    desc: "منصة رقمية متكاملة لقاعات الأفراح تجمع بين موقع تسويقي فاخر، نظام حجز، دفع، لوحة إدارة، دعوات رقمية، RSVP، رفع صور الضيوف، وتجربة كتاب ذكريات.",
                    image: "/assest/resize/qaser-alfarah.png",
                    link: "#",
                    slug: "qasr-al-farah",
                },
                {
                    title: "Curevie",
                    category: "تجربة رقمية طبية",
                    desc: "تجربة رقمية في المجال الصحي مبنية حول الثقة، الوضوح، العرض النظيف، وواجهة احترافية بطابع طبي.",
                    image: "/assest/curevie3.jpeg",
                    link: "#",
                    slug: "curevie",
                },
                {
                    title: "Horvath Survey",
                    category: "منصة استبيانات وبيانات أعمال",
                    desc: "تجربة استبيانات وجمع بيانات منظمة تركز على وضوح النماذج، سهولة الإدخال، واستخراج معلومات عملية للأعمال.",
                    image: "/assest/resize/horvath1.jpg",
                    link: "#",
                    slug: "horvath-survey",
                },
                {
                    title: "Manal Alhihi Educational Platform",
                    category: "منصة تعليمية",
                    desc: "منصة تعليمية مبنية حول تنظيم المحتوى، وضوح التنقل، وتجربة احترافية للطلاب والمستخدمين.",
                    image: "/assest/resize/manal-alhihi.png",
                    link: "#",
                    slug: "manal-alhihi",
                },
            ],
            cta: "المزيد على GitHub",
        },
        testimonials: {
            title: "إشارات الثقة",
            subtitle: "هذا الاستوديو مبني حول أسطح منتجات عملية وليس آراء عملاء وهمية.",
            items: [
                {
                    quote: "Mohammed Aldomi تعامل مع حضور Curevie الرقمي بطريقة منظمة وهادئة. النتيجة كانت تجربة واضحة، موثوقة، ومصقولة، وفي نفس الوقت حافظت على الجانب الإنساني الذي نهتم به.",
                    author: "الدكتور أحمد الأخرس",
                    role: "مدير شركة Curevie",
                },
                {
                    quote: "التعامل مع Dominase كان مريحاً واحترافياً من أول نقاش. فهم Mohammed Aldomi اتجاه العلامة بسرعة، وحوّل الفكرة إلى واجهة حادة، عملية، ومناسبة لمستخدمين حقيقيين.",
                    author: "سلطان الحاج",
                    role: "مدير شركة Inkspire",
                },
                {
                    quote: "النتيجة النهائية كان فيها التنظيم والثقة البصرية التي كنا نحتاجها. Mohammed Aldomi اهتم بالتفاصيل الصغيرة، وشرح اختياراته بوضوح، وقدّم عملاً رفع صورة الشركة فعلاً.",
                    author: "المهندس أحمد خالد",
                    role: "صاحب شركة هندسية",
                },
            ],
            cta: "ابدأ بناءً جاداً",
        },
        contact: {
            title: "لنبنِ شيئاً مفيداً",
            subtitle: "أرسل رسالة إذا كان عملك يحتاج موقعاً مصقولاً، واجهة بأسلوب SaaS، مسار حجز، أو نظاماً رقمياً أوضح.",
            info: {
                phone: "+962779667168",
                email: "mohammed.aldomi68@gmail.com",
                address: "عمّان، الأردن",
            },
            form: {
                name: "الاسم",
                email: "البريد الإلكتروني",
                phone: "رقم الهاتف",
                message: "تفاصيل المشروع",
                submit: "أرسل الرسالة",
            },
            portal: {
                eyebrow: "نقطة القرار",
                panelLabel: "التقاط الإشارة",
                fields: {
                    name: { label: "الاسم", placeholder: "اسمك الكامل" },
                    phone: { label: "رقم الهاتف", placeholder: "أفضل رقم للتواصل معك" },
                    company: { label: "اسم الشركة", placeholder: "اسم الشركة (اختياري)" },
                },
                submit: "ابدأ المحادثة",
                submitting: "جاري الإرسال…",
                errors: {
                    name: "الرجاء إدخال اسمك.",
                    phone: "الرجاء إدخال رقم الهاتف.",
                    submit: "حدث خطأ ما. حاول مرة أخرى، أو تواصل معي مباشرة بالأسفل.",
                    config: "نموذج التواصل غير مهيأ. الرجاء ضبط NEXT_PUBLIC_FORMSPREE_ENDPOINT.",
                },
                success: {
                    eyebrow: "تم استلام الإشارة",
                    title: "تم إرسال طلبك بنجاح",
                    body: "أخذت أول خطوة في القرار الذي قد يغيّر طريقة ظهور مشروعك للعالم. سيراجع Mohammed التفاصيل ويتواصل معك قريبًا.",
                    button: "إرسال رسالة أخرى",
                },
                channels: {
                    heading: "مسارات مباشرة",
                    whatsapp: { label: "راسلني على واتساب", caption: "واتساب", helper: "رد أسرع" },
                    phone: { label: "اتصل بي هاتفياً", caption: "اتصال", helper: "تواصل مباشر" },
                    email: { label: "أرسل بريداً إلكترونياً", caption: "بريد", helper: "تفاصيل رسمية" },
                },
            },
        },
        features: [
            {
                title: "تفكير منتج",
                desc: "كل قسم وشاشة وتفاعل يتم بناؤه حول ما يحتاج المستخدم أن يفهمه أو يفعله بعد ذلك.",
            },
            {
                title: "دقة في الواجهة",
                desc: "تخطيطات متجاوبة، حركة مصقولة، تسلسل بصري واضح، وتنفيذ واعٍ بالأداء عبر واجهات حديثة.",
            },
            {
                title: "سير عمل للأعمال",
                desc: "أنظمة عملية للحجز، لوحات التحكم، الاستبيانات، التعليم، الصحة، الدفع، وتشغيل المحتوى.",
            },
        ],
        problem: {
            title: "المواقع العامة لا تبني ثقة المنتج",
            description: "معظم مواقع الأعمال تبدو مقبولة لكنها لا تشرح العرض، لا توجه المستخدم، ولا تدعم العمليات الحقيقية. النتيجة حضور رقمي منفصل عن قيمة العمل نفسه.",
        },
        socialProof: {
            trustedBy: "مبني حول واجهات مشاريع حقيقية",
            testimonial: "\"المنتج الرقمي القوي يجب أن يبدو فاخراً على السطح وعملياً في الداخل.\"",
            attribution: "- Mohammed Aldomi، المؤسس",
        },
        solution: {
            title: "استوديو مبني حول أنظمة رقمية تعمل",
            benefits: [
                {
                    title: "عرض واضح",
                    desc: "صفحات فاخرة تجعل العرض والقصة ومسار الإجراء واضحين.",
                },
                {
                    title: "عمق تشغيلي",
                    desc: "واجهات للوحات التحكم، الحجوزات، النماذج، وسير عمل الشركات.",
                },
                {
                    title: "تجربة مصقولة",
                    desc: "حركة، مسافات، صور، وسلوك متجاوب مضبوط ليبدو حاداً ومقصوداً.",
                },
            ],
        },
        finalCTA: {
            title: "جاهز لبناء منتج رقمي أوضح؟",
            subtext: "أحضر المشروع، سياق العمل، والطموح. ستساعدك DOMINASE في تحويله إلى واجهة مصقولة يمكن للمستخدمين الوثوق بها.",
            primaryCTA: "ابدأ مشروعك",
            secondaryCTA: "شاهد الأعمال",
            reassurance: "متاح للمواقع المركزة، واجهات المنتجات، والأنظمة التشغيلية.",
        },
        footer: {
            tagline: "DOMINASE — Digital Product Studio by Mohammed Aldomi.",
            rights: "© 2026 DOMINASE. Built by Mohammed Aldomi.",
            links: ["الأعمال", "تواصل"],
        },
    },
};
