import type { Metadata } from "next";
import JsonLd from "@/components/JsonLd";
import MarketPageClient, { type MarketCopy } from "@/features/markets/MarketPageClient";
import "@/features/markets/markets.css";
import { SITE_URL } from "@/config/seo";

export const metadata: Metadata = {
  title: "شركة برمجة في الأردن | مواقع وأنظمة ومنصات",
  description: "DOMINASE شركة برمجة ومنتجات رقمية من عمّان. تطوير مواقع، أنظمة مخصصة، منصات تعليمية، مواقع وأنظمة عيادات وUX/UI للشركات والمشاريع في الأردن.",
  alternates: { canonical: "/markets/jordan" },
  openGraph: { title: "DOMINASE — Software Development in Jordan", description: "Websites, custom systems, education platforms and clinic digital products from Amman, Jordan.", url: `${SITE_URL}/markets/jordan`, type: "website" },
};

const copy: MarketCopy = {
  ar:{eyebrow:"DOMINASE / الأردن",title:"شركة برمجة في الأردن تبني الموقع والنظام حول طريقة عملك.",lead:"من عمّان، نبني مواقع ومنتجات رقمية للشركات والمدربين والعيادات والأعمال التي تحتاج تجربة أوضح ونظاماً يقلل العمل المبعثر.",intro:"السوق الأردني حساس للسعر، لكن العميل يقارن أيضاً بسرعة ويلاحظ الثقة والأداء ووضوح العرض. لذلك نبحث عن أصغر حل يعطي قيمة حقيقية: موقع يقود إلى الطلب، أو منصة تدير البيع والتعلم، أو نظام يجمع العملية في مكان واحد بدلاً من إضافة تقنية بلا حاجة.",needsTitle:"أكثر أنواع المشاريع التي نبنيها في الأردن",needs:[{title:"تطوير المواقع",body:"مواقع شركات وخدمات أسرع، أوضح على الهاتف ومهيأة تقنياً للبحث والتحويل.",href:"/services/web-development"},{title:"الأنظمة المخصصة",body:"إدارة عملاء وحجوزات وموظفون وصلاحيات وتقارير عندما تصبح الجداول وواتساب عائقاً.",href:"/services/custom-systems"},{title:"المنصات التعليمية",body:"منصة للمدرب أو الأكاديمية لإدارة المحتوى والطلاب والاختبارات والبيع.",href:"/services/education-platforms"},{title:"مواقع وأنظمة العيادات",body:"ثقة وإجراء واضح وحجز وقياس ومتابعة للفرص بدلاً من أن تنتهي الرحلة برسالة مبعثرة.",href:"/services/clinic-websites"}],approachTitle:"كيف نجعل المشروع عملياً للسوق المحلي؟",approach:["نحدد النتيجة التجارية أو التشغيلية قبل عدد الصفحات والمزايا.","نصمم العربية من اليمين إلى اليسار كواجهة أصلية ونختبرها على الهاتف.","نقسّم النطاق إلى نسخة أولى واضحة ثم نوسع حسب الاستخدام والميزانية.","نربط الموقع بالإجراء والحجز أو المتابعة عندما تكون هذه هي المشكلة الحقيقية.","نبني أساس الظهور في البحث ومحتوى واضحاً بدلاً من حشو الكلمات."],seoTitle:"الظهور في الأردن يبدأ عندما يعرف محرك البحث والعميل بدقة ما الذي تقدمه.",seoBody:"نربط صفحات الخدمات بالمقالات والأعمال، ونستخدم عناوين ومحتوى يخدم نية بحث حقيقية مثل شركة برمجة في الأردن، تطوير مواقع، أنظمة مخصصة أو منصات تعليمية. لا نعد بترتيب أول مضمون؛ نبني أساساً يستطيع المنافسة والتحسن مع المحتوى والقياس.",finalTitle:"لديك مشروع في الأردن؟",finalBody:"أرسل نوع المشروع والنتيجة التي تريدها. يطلب النموذج التفاعلي أقل قدر مفيد من المعلومات، ويعطينا سياقاً أفضل من سؤال السعر وحده.",finalCta:"ابدأ مشروعك"},
  en:{eyebrow:"DOMINASE / Jordan",title:"A software company in Jordan building websites and systems around how the work actually happens.",lead:"From Amman, we build digital products for companies, instructors, clinics, and service businesses that need a clearer customer experience and less scattered operations.",intro:"Jordanian buyers are cost-conscious but also compare trust, speed, clarity, and proof quickly. We therefore look for the smallest solution that creates real value instead of adding technology without a job.",needsTitle:"What we commonly build in Jordan",needs:[{title:"Web development",body:"Faster company and service websites shaped for mobile, search, and conversion.",href:"/services/web-development"},{title:"Custom systems",body:"CRM, booking, roles, staff, and reporting when spreadsheets and chat become operational friction.",href:"/services/custom-systems"},{title:"Education platforms",body:"Instructor and academy platforms for content, students, assessments, and sales.",href:"/services/education-platforms"},{title:"Clinic websites and systems",body:"Trust, CTA, booking, tracking, and follow-up instead of isolated messages.",href:"/services/clinic-websites"}],approachTitle:"How we keep the project practical",approach:["Define the commercial or operational outcome before page and feature counts.","Treat Arabic RTL as a first-class mobile experience.","Scope a clear MVP and expand from use and budget evidence.","Connect the website to booking or follow-up when that is the real constraint.","Build useful technical SEO and content instead of keyword stuffing."],seoTitle:"Search visibility starts with making the offer explicit to both people and search engines.",seoBody:"Service pages, useful articles, work proof, clear titles, and internal links create a stronger search foundation for relevant commercial queries in Jordan.",finalTitle:"Building something in Jordan?",finalBody:"Send the project type and the outcome you need. The guided form collects only the context that helps us respond usefully.",finalCta:"Start a project"}
};

export default function Page(){return <><JsonLd data={{"@context":"https://schema.org","@type":"WebPage",name:"Software development in Jordan — DOMINASE",url:`${SITE_URL}/markets/jordan`,about:{"@id":`${SITE_URL}/#organization`}}}/><MarketPageClient copy={copy}/></>}
